[MySQL]
  mysql_host = ""
  mysql_port = 3306
  mysql_username = ""
  mysql_password = ""
  hosted_in_aws_rds = false
  db = ""

[ssh_tunnel]
  use_ssh_tunnel = false
  ssh_host = ""
  ssh_port = 22
  ssh_username = ""
  ssh_password = ""
  ssh_private_key = ""
  ssh_key_passphrase = ""

[long_running_query]
  timeout_second = 10
